# Generated by Django 5.0.6 on 2024-06-28 15:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matric_number', models.CharField(max_length=11, unique=True)),
                ('full_name', models.CharField(max_length=200)),
                ('faculty', models.CharField(choices=[('Management Science', 'Management Science'), ('Agriculture', 'Agriculture'), ('Social Science', 'Social Science'), ('Education', 'Education'), ('Science', 'Science'), ('Arts', 'Arts'), ('Law', 'Law')], max_length=50)),
                ('department', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('gender', models.CharField(max_length=10)),
            ],
        ),
    ]
